### ISSUE TITLE
How Can I get seg_annotation_info.json?

### ISSUE THREAD

**Issue by Haobo-Liu** [JanEGerken/HEAL-SWIN#6]
Thanks to your excellent work, When I run "python heal_swin/data/segmentation/synwoodscape_merge_classes.py",I met the following errors:
Could not find seg_annotation_info.json file at /home/liusu/projects/depth_estimation/HEAL-SWIN/datasets/synwoodscape/semantic_annotations/seg_annotation_info.json

Could you give me some advices?
Thanks again!

**Comment by JanEGerken** [comment]
Hi,
Thanks for your interest in our work! If I remember correctly, that file should be part of the dataset. Did you download the dataset from this link: https://drive.google.com/drive/folders/1N5rrySiw1uh9kLeBuOblMbXJ09YsqO7I and point the `datasets` directory in the compute environment to the directory where you saved the dataset?

**Comment by Haobo-Liu** [comment]
> Hi, Thanks for your interest in our work! If I remember correctly, that file should be part of the dataset. Did you download the dataset from this link: https://drive.google.com/drive/folders/1N5rrySiw1uh9kLeBuOblMbXJ09YsqO7I and point the `datasets` directory in the compute environment to the directory where you saved the dataset?

So pity,I check again and again, but I still can't find this file, Could you send this file through email to me? My email address is 1142074652@qq.com. I appreciate it a lot!

**Comment by JanEGerken** [comment]
This is the file: [seg_annotation_info.json](https://github.com/user-attachments/files/17330714/seg_annotation_info.json)
